apiVersion: skaffold/v2beta28
kind: Config
build:
  artifacts:
    - image: workload
profiles:
  - name: blue
    build:
      artifacts:
        - image: blue
    deploy:
      kubectl:
        manifests:
          - k8s/blue.yaml
  - name: green
    build:
      artifacts:
        - image: green
    deploy:
      kubectl:
        manifests:
          - k8s/green.yaml
