apiVersion: skaffold/v2beta28
kind: Config

build:
  artifacts:
    - image: workload
      docker:
        buildArgs:
          COLOR: blue
      sync:
        manual:
          - src: 'www/**'
            dest: /var/www/html
  local:
    useDockerCLI: true
    useBuildkit: true


profiles:
  - name: blue
    build:
      artifacts:
        - image: blue
          docker:
            buildArgs:
              COLOR: blue
    deploy:
      kubectl:
        manifests:
          - k8s/blue.yaml
  - name: green
    build:
      artifacts:
        - image: green
          docker:
            dockerfile: Dockerfile
            buildArgs:
              COLOR: green
    deploy:
      kubectl:
        manifests:
          - k8s/green.yaml
