apiVersion: skaffold/v2beta28
kind: Config
build:
  artifacts:
    - image: workload
deploy:
  kubectl:
    manifests:
      - k8s/blue.yaml
profiles:
  - name: blue
    activation:
      - env: COLOR=blue
    build:
      artifacts:
        - image: blue
    deploy:
      kubectl:
        manifests:
          - k8s/blue.yaml
  - name: green
    activation:
      - env: COLOR=green
    build:
      artifacts:
        - image: green
    deploy:
      kubectl:
        manifests:
          - k8s/green.yaml
