apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-workload
  labels:
    app: blue-green-testing
    variant: blue
spec:
  selector:
    matchLabels:
      app: blue-green-testing
      variant: blue
  template:
    metadata:
      labels:
        app: blue-green-testing
        variant: blue
    spec:
      containers:
        - name: blue-workload
          image: blue
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: blue-workload
  labels:
    app: blue-green-testing
    variant: blue
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: blue-green-testing
    variant: blue
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: blue-workload
  labels:
    app: blue-green-testing
    variant: blue
spec:
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 70
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 90
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blue-workload
  minReplicas: 1
  maxReplicas: 10

