apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-workload
  labels:
    app: blue-green-testing
    instance: blue
spec:
  selector:
    matchLabels:
      app: blue-green-testing
      instance: blue
  template:
    metadata:
      labels:
        app: blue-green-testing
        instance: blue
    spec:
      containers:
        - name: workload
          image: blue
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "10m"
              memory: "10Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: blue-workload
  labels:
    app: blue-green-testing
    instance: blue
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: blue-green-testing
    instance: blue
---
# Requires metrics-server:
# kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: blue-workload
  labels:
    app: blue-green-testing
    instance: blue
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blue-workload
  minReplicas: 1
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
