apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-workload
  labels:
    app: blue-green-testing
    instance: green
spec:
  selector:
    matchLabels:
      app: blue-green-testing
      instance: green
  template:
    metadata:
      labels:
        app: blue-green-testing
        instance: green
    spec:
      containers:
        - name: workload
          image: green
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: green-workload
  labels:
    app: blue-green-testing
    instance: green
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: blue-green-testing
    instance: green
---
# Requires metrics-server:
# kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: green-workload
  labels:
    app: blue-green-testing
    instance: green
spec:
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 70
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 90
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: green-workload
  minReplicas: 1
  maxReplicas: 10
