apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-workload
  labels:
    app: blue-green-testing
    variant: green
spec:
  selector:
    matchLabels:
      app: blue-green-testing
      variant: green
  template:
    metadata:
      labels:
        app: blue-green-testing
        variant: green
    spec:
      containers:
        - name: green-workload
          image: green
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: green-workload
  labels:
    app: blue-green-testing
    variant: green
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: blue-green-testing
    variant: green
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: green-workload
  labels:
    app: blue-green-testing
    variant: green
spec:
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 70
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 90
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: green-workload
  minReplicas: 1
  maxReplicas: 10
